version: '3'
services:
  root-plant:
    container_name: 'gateway'
    hostname: 'gateway'
    restart: always
    build: .
    ports:
      - '3300:3300'

networks:
  default:
    external:
      name: test
