version: "3"
services:
  root-plant:
    container_name: "gateway-p2p"
    hostname: "gateway-p2p"
    restart: always
    build: .
    ports:
      - "3300:3300"

networks:
  default:
    external:
      name: rootenergy
