apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: dev-gateway
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-gateway
  template:
    metadata:
      labels:
        app: dev-gateway
    spec:
      imagePullSecrets:
        - name: gcrio
      containers:
        - name: dev-gateway
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 80
      #     volumeMounts:
      #       - mountPath: /tmp2
      #         name: env
      # volumes:
      #   - configMap:
      #       defaultMode: 256
      #       name: dev-env
      #       optional: false
      #     name: env
